services:
  - type: web
    name: eduspace
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_LOGIN
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
